steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.cloudbuild'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/apache-devlake/devlake:${_IMAGE_TAG}'
      - '.'
    dir: 'backend'
    waitFor: ['-']

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/apache-devlake/devlake:${_IMAGE_TAG}'

substitutions:
  _IMAGE_TAG: 'tempo-latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'