imageTag: "pr-8765-tempo-4931204"

lake:
  encryptionSecret:
    secret: "GBQSWJGGPWWXJASUEQPJUYCZUHCWVGGKLXDJLDPEFOPJSARSNJENGXWFNIXKSDJKODWIKFKUJUHKIPBYDXGRJXTLXDHSTLHIVEFNMRKETUKHSDIHEWEZJMIERJUUZPRW"
  image:
    repository: europe-west1-docker.pkg.dev/abs-digital-playground/apache-devlake/devlake
    pullPolicy: Always
  envs:
    API_TIMEOUT: "120s"
    API_RETRY: "3"
    API_REQUESTS_PER_HOUR: "10000"
    PIPELINE_MAX_PARALLEL: "1"
    IN_SECURE_SKIP_VERIFY: "false"
    LOGGING_LEVEL: "info"
    JIRA_JQL_AUTO_FULL_REFRESH: "true"
    FORCE_MIGRATION: "true"

ui:
  image:
    repository: europe-west1-docker.pkg.dev/abs-digital-playground/apache-devlake/devlake-config-ui
    tag: "pr-8765-tempo-4931204"
    pullPolicy: Always

grafana:
  enabled: true
  image:
    repository: devlake.docker.scarf.sh/apache/devlake-dashboard

mysql:
  useExternal: false
  rootPassword: devlake-admin
  username: merico
  password: merico
  database: lake
  storage:
    type: pvc
    size: 20Gi

ingress:
  enabled: true
  enableHttps: false
  useDefaultNginx: false
  className: traefik
  hostname: devlake.ces.abssrv.it
